# Generated by Django 4.1.4 on 2022-12-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_alter_category_options_secondarychallenge_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primarychallenge",
            name="description",
        ),
        migrations.RemoveField(
            model_name="secondarychallenge",
            name="description",
        ),
    ]
