# Generated by Django 4.1.4 on 2022-12-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0003_remove_primarychallenge_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarychallenge",
            name="additional_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="secondarychallenge",
            name="additional_info",
            field=models.TextField(blank=True),
        ),
    ]
