# Generated by Django 4.1.4 on 2022-12-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0006_alter_game_steam_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="steam_link",
            new_name="external_link",
        ),
    ]
