# Generated by Django 4.1.4 on 2022-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0007_rename_steam_link_game_external_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
