# Generated by Django 4.1.4 on 2022-12-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0008_alter_game_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="external_link",
            field=models.URLField(),
        ),
    ]
