# Generated by Django 4.1.4 on 2022-12-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0009_alter_game_external_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="external_link",
            new_name="steam_link",
        ),
    ]
