# Generated by Django 4.1.4 on 2022-12-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0010_rename_external_link_game_steam_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="external_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="steam_link",
            field=models.URLField(blank=True),
        ),
    ]
