# Generated by Django 4.1.4 on 2022-12-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_developer_game_developer"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="despaced",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
