# Generated by Django 4.1.4 on 2022-12-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="primarychallenge",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="secondarychallenge",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
